### ISSUE TITLE
Create an user for the trainer

### ISSUE THREAD

**Issue by gsaurin** [altimetrik-onboarding-uy/gsaurin-compensations#16]
Create an user for your trainer with the following format:
Name: Lorena Xavier
Username:  [your Altimetrik email user].evaluation@altimetrik.com
For example if your name is Juan Perez, your Altimetrik email user should be jperez, so your supervisor username would be: jperez.evaluation@altimetrik.com
Email: rjuliani@altimetrik.com
User License: Salesforce 
Profile: System Administrator

**Comment by rjulianialtimetrik** [comment]
This is not a User Story since it does not add functionality to the user.
