### ISSUE TITLE
Clone an existing profile and grant access to a custom object

### ISSUE THREAD

**Issue by gsaurin** [altimetrik-onboarding-uy/gsaurin-compensations#17]
Clone the Standard Platform User profile (under Salesforce Platform user license), name it Manager Custom and grant permissions over the mentioned object, also create an user with the custom profile using the next format:
Name: My Manager
Username:  [your Altimetrik email user].manager@altimetrik.com 
For example: jperez.manager@altimetrik.com
Email: your Altimetrik email
User License: Salesforce Platform
Profile: Manager Custom
Once created, set this user as your own Manager (in your user profile).

**Comment by rjulianialtimetrik** [comment]
@gsaurin this is not a user story, this is just a task because it does not add functionality to the users. Please change the label to something like "Task" or "To-Do"
